# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: omakran <omakran@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/11 18:11:04 by omakran           #+#    #+#              #
#    Updated: 2024/01/11 18:30:54 by omakran          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone

CC = c++

FLAGS = -Wall -Wextra -Werror -std=c++98

RMF = rm -RMF

all: $(NAME)


clean:
	$(RM) $(NAME)


fclean:
	











.PHONY: all clean re